### ISSUE TITLE
About the seed setting.

### ISSUE THREAD

**Issue by Zawo1995** [DeepGraphLearning/KnowledgeGraphEmbedding#21]
Thanks for sharing the wonderful code :)
When I  reproduce the RototE，I find the result is different each time(but just a little),such as loss.mr,mrr,etc.So I find that your code didn't contain ant code about  seed setting code,like
`seed = 42
np.random.seed(seed)
torch.manual_seed(seed)
if is_cuda:
    torch.cuda.manual_seed_all(seed)`

It is different from the tutorial ever I did.
Could you give some explanation about  your thinking about that?

Looking forward to your repeat,sorry for asking so shallow issues QAQ.

**Comment by Edward-Sun** [comment]
Yes. We didn't set random seeds because we find that the results are insensitive to different random seeds. As we report in the paper, the variance is usually only 0.000-0.001.

It is common that when the hidden size is large enough, the random initialization won't influence much on the final results.
